CHECK_POTENTIAL_PLOT_INVERVAL = 8
ZONE_RADIUS = 80
MAX_PLOT_RADIUS = 10
MIN_PLOT_RADIUS = 6
NUMBER_OF_PLOTS = 10

# plot selection weights
STEEPNESS_WEIGHTING = 0.6
DISTANCE_WEIGHTING = 0.3
HEIGHT_DELTA_WEIGHTING = 0.1

# terraforming settings 
FILL_INTERVAL = 4
LOOK_AHEAD = 6

TOWN_CENTER_RADIUS = 10
GENERATE_HOUSES = True